modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="mc_mod_i18n_hardcoded_patch"
version="${mod_version}"
displayName="${mod_name}"
description='''Runtime consumer for mc-mod-i18n hardcoded-map.json.'''

[[dependencies.mc_mod_i18n_hardcoded_patch]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.mc_mod_i18n_hardcoded_patch]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
